// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7bBUbsCdrdSm9kxiydawMvaEpuNE9hB4',
    appId: '1:1053901544741:web:53b843cc36315d9b3b4ecc',
    messagingSenderId: '1053901544741',
    projectId: 'askngo-41a7b',
    authDomain: 'askngo-41a7b.firebaseapp.com',
    storageBucket: 'askngo-41a7b.firebasestorage.app',
    measurementId: 'G-P01KD0CGRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaXciKwjsJdR4ejFiVG_VkfY34ec9spn4',
    appId: '1:1053901544741:android:70e3da14d16531d63b4ecc',
    messagingSenderId: '1053901544741',
    projectId: 'askngo-41a7b',
    storageBucket: 'askngo-41a7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIXh3lWMyavjinnHkqfZGtLVxh0lUcMck',
    appId: '1:1053901544741:ios:aaeddda5e77201e93b4ecc',
    messagingSenderId: '1053901544741',
    projectId: 'askngo-41a7b',
    storageBucket: 'askngo-41a7b.firebasestorage.app',
    iosClientId: '1053901544741-c3smomutdfdnf7fb16gpli9273gnbpv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.askngo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIXh3lWMyavjinnHkqfZGtLVxh0lUcMck',
    appId: '1:1053901544741:ios:aaeddda5e77201e93b4ecc',
    messagingSenderId: '1053901544741',
    projectId: 'askngo-41a7b',
    storageBucket: 'askngo-41a7b.firebasestorage.app',
    iosClientId: '1053901544741-c3smomutdfdnf7fb16gpli9273gnbpv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.askngo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7bBUbsCdrdSm9kxiydawMvaEpuNE9hB4',
    appId: '1:1053901544741:web:1022b8ce09d1ceae3b4ecc',
    messagingSenderId: '1053901544741',
    projectId: 'askngo-41a7b',
    authDomain: 'askngo-41a7b.firebaseapp.com',
    storageBucket: 'askngo-41a7b.firebasestorage.app',
    measurementId: 'G-4RLJ4DJCZC',
  );
}
